name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.9'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build

      - name: Size check (size-limit)
        run: bun run size:ci

      - name: Upload bundle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bundle-report
          path: dist/bundle-report.html

      - name: Storybook build
        run: bun run storybook:build

      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium

      - name: E2E (Playwright)
        run: bun run e2e
